"""Create users table

Revision ID: 612af829049d
Revises: 9b1338f9bf10
Create Date: 2026-07-10 10:30:50.833584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '612af829049d'
down_revision = '9b1338f9bf10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['filename'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('users')
    # ### end Alembic commands ###
